# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 09:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='data',
            old_name='meassage',
            new_name='message',
        ),
    ]
