# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-22 10:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20160622_0936'),
    ]

    operations = [
        migrations.AlterField(
            model_name='data',
            name='date',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='data',
            name='message',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='data',
            name='time',
            field=models.TextField(),
        ),
    ]
